# Generated by Django 2.2 on 2020-02-25 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='about title'),
            preserve_default=False,
        ),
    ]
